server:
  port: 8083

spring:
  application:
    name: service-consumer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka,http://localhost:8079/eureka
    registry-fetch-interval-seconds: 5

service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能


logging:
  level:
    com:mycen: debug
