server:
  port: 8080

spring:
  application:
    name: mycen-eureka


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8079/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
